#!/bin/sh -x
# Restart appropriate service depending on files changed.
#
# Handle all services from this same repo.
#
# This script should only be used to restart containers, do not use it to
# modify files, files it touches will have wrong permissions.

if [ -n "`echo "$GIT_CHANGED_FILES" | grep 'Sensibilit\303\251/'`" -o -z "$GIT_PREVIOUS_COMMIT_HASH" ]; then
    if [ -n "`docker ps --format '{{.Names}}' | grep sensibilite_climatique_ouranos`" ]; then
        # Restart only if files under Sensibilité/ changes or on
        # first clone when GIT_PREVIOUS_COMMIT_HASH is emtpy.
        docker restart sensibilite_climatique_ouranos  # container name from pavics_panel_ouranos_deploy repo
    fi
fi
